# Generated by Django 2.0.4 on 2018-05-09 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=254)),
                ('matriculation', models.CharField(blank=True, max_length=254, unique=True)),
                ('picture', models.ImageField(null=True, upload_to='%Y/%m/%d')),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('birthPlace', models.CharField(blank=True, max_length=254)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Teacher'), (3, 'Student')], null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_Department', to='Administration.Department', verbose_name='Student Department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReg', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_Course', to='Administration.Courses', verbose_name='Student Course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Student_Course', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_level', models.CharField(blank=True, max_length=255, null=True, verbose_name='Level')),
                ('code_level', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_level', to='BaseUser.StudentLevel'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
