# Generated by Django 2.0.4 on 2018-05-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree_programm',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Male'), (5, 'Femaile')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.IntegerField(default=120, unique=True, verbose_name='ID Card Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(6, 'Married'), (7, 'Single')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, max_length=254, verbose_name='Region of Origin'),
        ),
    ]
