# Generated by Django 2.0.4 on 2018-05-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0002_auto_20180518_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthPlace',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree_programm',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_Department', to='Administration.Department', verbose_name='Student Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID Card Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_level', to='BaseUser.StudentLevel'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matriculation',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Region of Origin'),
        ),
    ]
