# Generated by Django 2.0.4 on 2018-05-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_auto_20180518_1517'),
        ('BaseUser', '0006_auto_20180518_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Academic_year', to='Administration.AcademicYear', verbose_name='Academic Year'),
        ),
    ]
