# Generated by Django 2.0.4 on 2018-05-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0008_auto_20180520_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='type_course',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
