# Generated by Django 2.0.4 on 2018-05-21 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0009_studentcourse_type_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercourses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Lecturer'),
        ),
    ]
