# Generated by Django 2.0.4 on 2018-05-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0004_auto_20180521_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuousassessment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (0, 'Closed')], default=1, verbose_name='CA Status'),
            preserve_default=False,
        ),
    ]
