# Generated by Django 2.0.4 on 2018-05-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0005_continuousassessment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (0, 'Closed')], default=1, verbose_name='Exam Status'),
            preserve_default=False,
        ),
    ]
