# Generated by Django 2.0.4 on 2018-05-26 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Administration', '0008_auto_20180521_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resit_start', models.DateField(unique=True)),
                ('resit_end', models.DateField(unique=True)),
                ('resit', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (0, 'Closed')], verbose_name='Resit Status')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Semester_Resit', to='Administration.Semester', verbose_name='Semester Resit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
