# Generated by Django 2.0.4 on 2018-06-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0009_resit'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semester_s', to='Administration.Semester', verbose_name='Semester.'),
            preserve_default=False,
        ),
    ]
