# Generated by Django 2.0.4 on 2018-06-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0010_marks_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Averages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Average Score')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_Avg', to='Administration.Courses', verbose_name='Course Average')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_Avg', to='Administration.Semester', verbose_name='Semester.')),
            ],
        ),
    ]
