# Generated by Django 2.0.4 on 2018-06-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0011_courseaverage_finalscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaverage',
            name='credit',
            field=models.IntegerField(default=1, verbose_name='Credit Value'),
            preserve_default=False,
        ),
    ]
