# Generated by Django 2.0.4 on 2018-06-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0011_averages'),
    ]

    operations = [
        migrations.AddField(
            model_name='averages',
            name='divisor',
            field=models.IntegerField(default=0, verbose_name='Divisor'),
            preserve_default=False,
        ),
    ]
