# Generated by Django 2.0.4 on 2018-06-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0012_averages_divisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='averages',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Total Score'),
            preserve_default=False,
        ),
    ]
