# Generated by Django 2.0.4 on 2018-06-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0012_courseaverage_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='credit',
            field=models.IntegerField(default=3, verbose_name='Credit Value'),
            preserve_default=False,
        ),
    ]
