# Generated by Django 2.0.4 on 2018-06-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0013_marks_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaverage',
            name='academic_year',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Academic_Year', to='Administration.AcademicYear', verbose_name='School Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='academic_year',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='AcademicYear', to='Administration.AcademicYear', verbose_name='School Year'),
            preserve_default=False,
        ),
    ]
