# Generated by Django 2.0.4 on 2018-06-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0014_auto_20180611_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaverage',
            name='course_exam',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Course Exam'),
        ),
        migrations.AddField(
            model_name='courseaverage',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Exam Score'),
        ),
        migrations.AddField(
            model_name='courseaverage',
            name='grade_point',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Grade points'),
        ),
    ]
